# Generated by Django 4.2.3 on 2023-07-11 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teloenvio', '0002_remove_pedidos_idusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='idUsuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
