# Generated by Django 4.2.3 on 2023-07-11 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teloenvio', '0005_estado_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='id_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teloenvio.estado_pedido'),
        ),
    ]
