# Generated by Django 4.2.3 on 2023-07-11 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teloenvio', '0006_pedidos_id_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='estado_pedido',
        ),
    ]
