# Generated by Django 4.2.3 on 2023-07-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teloenvio', '0007_remove_pedidos_estado_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='id_cliente',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='comuna_cliente',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='direccion_cliente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='telefono_cliente',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
    ]
