# Generated by Django 4.2.3 on 2023-07-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teloenvio', '0008_remove_pedidos_id_cliente_pedidos_comuna_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='email_cliente',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
    ]
