# Generated by Django 4.2.3 on 2023-07-11 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teloenvio', '0009_pedidos_email_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id_productor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teloenvio.productores'),
        ),
    ]
